=head1 ActivePerl 5.16 Change Log

For the latest information on ActivePerl, please see:

    http://www.ActiveState.com/ActivePerl/

=head2 Build 1603 March, 2013
 
Build 1603 is based on Perl 5.16.3 plus additional selected changes.
 
I<Bug Fixes and Changes since build 1602>
 
=over 3
 
=item *

Significant changes that have occurred in the Perl 5.16.3 release are
documented in L<perl5163delta>.

=item *

Most bundled modules have been updated to their latest released
version from CPAN.  Use the C<ppm query> command to check the exact
version included in this release.

=back

=head2 Build 1602 November, 2012
 
Build 1602 is based on Perl 5.16.2 plus additional selected changes.
 
I<Bug Fixes and Changes since build 1601>
 
=over 3
 
=item *

Significant changes that have occurred in the Perl 5.16.2 release are
documented in L<perl5162delta>.

=item *

Most bundled modules have been updated to their latest released
version from CPAN.  Use the C<ppm query> command to check the exact
version included in this release.

=back

=head2 Build 1601 August, 2012
 
Build 1601 is based on Perl 5.16.1 plus additional selected changes.
 
I<Bug Fixes and Changes since build 1600>
 
=over 3
 
=item *

The Windows 64-bit version of ActivePerl now supports building modules using
the MinGW64 GCC compiler.  You can download this compiler via PPM if you
don't want to use the Windows 2003 Platform SDK compiler:

    ppm install MinGW64

ActivePerl 5.16.1.1601 will download and install this package automatically
if you try to build a Perl module and don't have a compiler available on
your C<PATH>.

=item *

On OS X ActivePerl will now automatically detect various versions of XCode
and use the compiler and tools included in that app if you don't have the
I<Commandline Tools for OS X> installed.

=item *

Significant changes that have occurred in the Perl 5.16.1 release are
documented in L<perl5161delta>.

=item *

Most bundled modules have been updated to their latest released
version from CPAN.  Use the C<ppm query> command to check the exact
version included in this release.

=back

=head2 Build 1600 Jun 1, 2012

I<What's new in the 1600 Series>

=over 3

=item *

This build corresponds to the Perl 5.16.0 source code release.

=item *

The 1600 series builds of ActivePerl are not binary compatible with
builds in the 600, 800, 1000, 1200 or 1400 series.  Any extensions built using binaries
from the ActivePerl 600, 800, 1000, 1200 or 1400 series will need to be recompiled.
Note especially that this applies to PPM packages that may have been
built for 600, 800, 1000, 1200 or 1400 series builds.

=item *

Significant changes that have occurred in the 5.16.0 release
are documented in L<perl5160delta>.

=item *

Most bundled distributions have been updated to their latest released
version from CPAN.  Use the C<ppm list> command to check the exact
version included in this release.

=back
